"""add refund_amount to refund_cases

Revision ID: 5fdb0edf10cb
Revises: 960d24882cb5
Create Date: 2026-09-18 10:28:43.006158

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "5fdb0edf10cb"
down_revision: Union[str, Sequence[str], None] = "960d24882cb5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("refund_cases", schema=None) as batch_op:
        batch_op.add_column(sa.Column("refund_amount", sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("refund_cases", schema=None) as batch_op:
        batch_op.drop_column("refund_amount")

    # ### end Alembic commands ###
