"""make refund_decision confidence nullable

Revision ID: 960d24882cb5
Revises: a50d4334d557
Create Date: 2026-09-17 17:15:56.057279

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "960d24882cb5"
down_revision: Union[str, Sequence[str], None] = "a50d4334d557"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("refund_decisions", schema=None) as batch_op:
        batch_op.alter_column("confidence", existing_type=sa.FLOAT(), nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("refund_decisions", schema=None) as batch_op:
        batch_op.alter_column("confidence", existing_type=sa.FLOAT(), nullable=False)

    # ### end Alembic commands ###
