"""add order, refund case, policy document models

Revision ID: a50d4334d557
Revises: 0aa6dc86562c
Create Date: 2026-09-17 15:50:13.066244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a50d4334d557'
down_revision: Union[str, Sequence[str], None] = '0aa6dc86562c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=False),
    sa.Column('customer_email', sa.String(length=255), nullable=False),
    sa.Column('purchased_at', sa.Date(), nullable=False),
    sa.Column('return_window_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_order_id'), 'orders', ['order_id'], unique=True)
    op.create_table('policy_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doc_id', sa.String(length=32), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_documents_doc_id'), 'policy_documents', ['doc_id'], unique=True)
    op.create_table('refund_cases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.String(length=32), nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=False),
    sa.Column('user_message', sa.Text(), nullable=False),
    sa.Column('image_refs', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('flagged_reason', sa.Text(), nullable=True),
    sa.Column('awaiting_human_since', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refund_cases_case_id'), 'refund_cases', ['case_id'], unique=True)
    op.create_index(op.f('ix_refund_cases_order_id'), 'refund_cases', ['order_id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.String(length=64), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_item_id'), 'order_items', ['item_id'], unique=True)
    op.create_table('refund_decisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.String(length=32), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('requires_human', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['refund_cases.case_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refund_decisions')
    op.drop_index(op.f('ix_order_items_item_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_refund_cases_order_id'), table_name='refund_cases')
    op.drop_index(op.f('ix_refund_cases_case_id'), table_name='refund_cases')
    op.drop_table('refund_cases')
    op.drop_index(op.f('ix_policy_documents_doc_id'), table_name='policy_documents')
    op.drop_table('policy_documents')
    op.drop_index(op.f('ix_orders_order_id'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
